'use client';

import { useEffect, useState, useCallback, useRef } from 'react';
// 確保已安裝: npm install @supabase/supabase-js
import { createClient as createSupabaseClient } from '@supabase/supabase-js';

// ==========================================
// [⚠️ 環境切換說明]
// 目前預設開啟 [模擬模式]。
// 若要部署到 Vercel (正式環境)，請：
// 1. 解除下方 [A] 的註解
// 2. 刪除或註解掉 [B] 的內容 (但保留變數宣告 let mockDb...)
//
// [🛠️ SQL 修復指令 - 解決無法寫入權限表問題]
// 請到 Supabase SQL Editor 執行：
/*
  create table if not exists user_permissions (
    id bigint generated by default as identity primary key,
    email text not null unique,
    is_admin boolean default false,
    is_disabled boolean default false,
    user_name text,
    id_last4 text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
  );
  
  alter table user_permissions enable row level security;
  
  -- 1. 允許所有人讀取 (讓前端能判斷權限)
  create policy "Allow read for all" on user_permissions for select to public using (true);
  
  -- 2. 關鍵：允許所有人新增 (解決註冊時無法寫入的問題)
  create policy "Allow insert for all" on user_permissions for insert to public with check (true);
  
  -- 3. 允許所有人修改 (讓管理員能改狀態，或使用者改自己資料)
  create policy "Allow update for all" on user_permissions for update to public using (true);
*/
// ==========================================

// --- 全域變數宣告 ---
let mockUser: any = null;
let mockDb: any = undefined;

// --- [A. 正式連線區塊] (請在 VS Code 中解除這裡的註解) ---
/*
const createClient = () => {
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || '';
  const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || '';
  return createSupabaseClient(supabaseUrl, supabaseKey);
};
*/

const createClient = () => {
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || '';
  const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || '';
  return createSupabaseClient(supabaseUrl, supabaseKey);
};


export default function RegistrationApp() {
  const [notes, setNotes] = useState<any[]>([]);
  const [bulletins, setBulletins] = useState<any[]>([]);
  const [allUsers, setAllUsers] = useState<any[]>([]); 
  const [user, setUser] = useState<any>(null);
  
  const [teamBigOptions, setTeamBigOptions] = useState<any[]>([]);
  const [teamSmallOptions, setTeamSmallOptions] = useState<any[]>([]);
  const [newOptionValue, setNewOptionValue] = useState('');
  const [selectedCategory, setSelectedCategory] = useState('');
  
  const [username, setUsername] = useState('');
  const [idLast4, setIdLast4] = useState(''); 
  const [password, setPassword] = useState('');
  const [loading, setLoading] = useState(false);
  const [isAdmin, setIsAdmin] = useState(false);
  
  const [isLoginMode, setIsLoginMode] = useState(true);
  const [activeTab, setActiveTab] = useState<'form' | 'history' | 'admin_data' | 'admin_users' | 'admin_settings' | 'bulletin'>('bulletin');
  const [filterMonth, setFilterMonth] = useState('');

  const [bulletinText, setBulletinText] = useState('');
  const [bulletinImage, setBulletinImage] = useState('');
  const fileInputRef = useRef<HTMLInputElement>(null);

  const [showPwdModal, setShowPwdModal] = useState(false);
  const [newPassword, setNewPassword] = useState('');
  const [pwdTargetUser, setPwdTargetUser] = useState<any>(null);

  const [addUserName, setAddUserName] = useState('');
  const [addUserLast4, setAddUserLast4] = useState('');
  const [addUserPwd, setAddUserPwd] = useState('');

  const ADMIN_ACCOUNT = 'admin'; 

  const [formData, setFormData] = useState({
    team_big: '', 
    team_small: '',
    monastery: '',
    real_name: '',
    dharma_name: '',
    action_type: '新增',
    start_date: '',
    start_time: '',
    end_date: '',
    end_time: '',
    need_help: false,
    memo: ''
  });
  
  const [supabase] = useState(() => createClient());
  const FAKE_DOMAIN = "@my-notes.com";

  // === 工具函式 ===
  const encodeName = (name: string) => {
    try {
      let hex = '';
      for (let i = 0; i < name.length; i++) {
        const char = name.charCodeAt(i).toString(16);
        hex += ('0000' + char).slice(-4);
      }
      return hex;
    } catch { return name; }
  };

  const decodeName = (email: string) => {
    try {
      const hex = email.split('@')[0];
      let str = '';
      for (let i = 0; i < hex.length; i += 4) {
        str += String.fromCharCode(parseInt(hex.substr(i, 4), 16));
      }
      return str;
    } catch { return email ? email.split('@')[0] : '使用者'; }
  };

  const getDisplayNameOnly = (email: string) => {
    const fullName = decodeName(email);
    if (fullName.length > 4 && !isNaN(Number(fullName.slice(-4)))) {
      return fullName.slice(0, -4);
    }
    return fullName;
  };

  const getIdLast4FromEmail = (email: string) => {
    if (!email) return '';
    const fullName = decodeName(email);
    if (fullName.length > 4 && !isNaN(Number(fullName.slice(-4)))) {
      return fullName.slice(-4);
    }
    return '';
  };

  const isExpired = (endDate: string, endTime: string) => {
    if (!endDate) return false;
    const endDateTimeStr = `${endDate}T${endTime || '23:59:59'}`;
    const endDateTime = new Date(endDateTimeStr);
    const now = new Date();
    return endDateTime < now;
  };

  const getTomorrowDate = () => {
    const date = new Date();
    date.setDate(date.getDate() + 1);
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, '0');
    const day = String(date.getDate()).padStart(2, '0');
    return `${year}-${month}-${day}`;
  };
  const minStartDate = getTomorrowDate();

  const handleLogout = useCallback(async () => {
    await supabase.auth.signOut();
    setUser(null);
    setNotes([]);
    setBulletins([]);
    setUsername('');
    setIdLast4('');
    setPassword('');
    setIsAdmin(false);
    setIsLoginMode(true);
    setActiveTab('bulletin');
  }, [supabase.auth]);

  const checkUserStatus = useCallback(async (email: string) => {
      if (!email) return;
      try {
          const { data } = await supabase
            .from('user_permissions')
            .select('is_admin, is_disabled')
            .eq('email', email)
            .single();
          
          if (data) {
              if (data.is_disabled) {
                  alert('您的帳號已被禁用，無法進入系統。');
                  await handleLogout();
                  return;
              }
              if (data.is_admin === true) setIsAdmin(true);
              else setIsAdmin(false);
          }
      } catch (e) { console.error(e); }
  }, [supabase, handleLogout]);

  const fetchOptions = useCallback(async () => {
    try {
      const { data: bigData } = await supabase.from('system_options').select('*').eq('category', 'team_big').order('created_at', { ascending: true }); 
      setTeamBigOptions(bigData || []);
      if (bigData && bigData.length > 0) setFormData(prev => ({...prev, team_big: prev.team_big || bigData[0].value}));
      else setTeamBigOptions([{id: 0, value: '觀音隊'}]); 

      const { data: smallData } = await supabase.from('system_options').select('*').eq('category', 'team_small').order('created_at', { ascending: true });
      setTeamSmallOptions(smallData || []);
      if (smallData && smallData.length > 0) setFormData(prev => ({...prev, team_small: prev.team_small || smallData[0].value}));
      else setTeamSmallOptions([{id: 0, value: '第1小隊'}]); 
    } catch (e) { console.error(e); }
  }, [supabase]);

  const handleInitializeDefaults = async () => {
      if (!confirm('確定要匯入預設選項嗎？')) return;
      setLoading(true);
      const defaultBig = ['觀音隊', '文殊隊', '普賢隊', '地藏隊', '彌勒隊'];
      const defaultSmall = ['第1小隊', '第2小隊', '第3小隊', '第4小隊', '第5小隊'];
      const insertPayload = [
          ...defaultBig.map(v => ({ category: 'team_big', value: v })),
          ...defaultSmall.map(v => ({ category: 'team_small', value: v }))
      ];
      const { error } = await supabase.from('system_options').insert(insertPayload);
      if (error) alert('匯入失敗：' + error.message);
      else {
          alert('預設選項匯入成功！');
          fetchOptions();
      }
      setLoading(false);
  };

  const handleAddOption = async (category: 'team_big' | 'team_small') => {
      if (!newOptionValue.trim()) return alert('請輸入選項名稱');
      setLoading(true);
      const { error } = await supabase.from('system_options').insert([{ category, value: newOptionValue.trim() }]);
      if (error) alert('新增失敗'); else { setNewOptionValue(''); fetchOptions(); }
      setLoading(false);
  };

  const handleDeleteOption = async (id: number) => {
      if (!confirm('確定刪除此選項？')) return;
      setLoading(true);
      const { error } = await supabase.from('system_options').delete().eq('id', id);
      if (error) alert('刪除失敗'); else fetchOptions();
      setLoading(false);
  };

  const exportToExcel = () => {
    const dataToExport = getFilteredNotes();
    if (dataToExport.length === 0) { alert("目前沒有資料"); return; }
    const headers = ["大隊", "小隊", "精舍", "姓名", "身分證", "法名", "動作", "開始日", "開始時", "結束日", "結束時", "協助", "備註", "登記時間", "填表人", "已刪除"];
    const csvRows = [
      headers.join(','),
      ...dataToExport.map(note => [
        note.team_big, note.team_small, note.monastery, note.real_name, note.id_2, note.dharma_name, note.action_type,
        note.start_date, note.start_time, note.end_date, note.end_time, note.need_help ? '是' : '否', `"${(note.memo || '').replace(/"/g, '""')}"`,
        new Date(note.created_at).toLocaleDateString(), note.sign_name || '', note.is_deleted ? '是' : ''
      ].join(','))
    ];
    const csvString = csvRows.join('\n');
    const blob = new Blob(["\ufeff" + csvString], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `export.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const getFilteredNotes = () => {
    if (!filterMonth) return notes; 
    return notes.filter(note => note.start_date && note.start_date.startsWith(filterMonth));
  };

  const handleImageUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onloadend = () => setBulletinImage(reader.result as string);
      reader.readAsDataURL(file);
    }
  };

  const handlePostBulletin = async () => {
    if (!bulletinText && !bulletinImage) return alert('請輸入內容');
    setLoading(true);
    const { error } = await supabase.from('bulletins').insert([{ content: bulletinText, image_url: bulletinImage }]);
    if (error) alert('失敗:' + error.message); else { alert('成功'); setBulletinText(''); setBulletinImage(''); fetchBulletins(); }
    setLoading(false);
  };

  const handleDeleteBulletin = async (id: number) => {
    if (!confirm('刪除?')) return;
    const { error } = await supabase.from('bulletins').delete().eq('id', id);
    if (!error) { alert('已刪除'); fetchBulletins(); }
  };

  const handleToggleDeleteNote = async (id: number, currentStatus: boolean) => {
    if (!currentStatus && !confirm('確定刪除?')) return;
    setLoading(true);
    const { data, error } = await supabase.from('notes').update({ is_deleted: !currentStatus }).eq('id', id).select();
    if (error || (data && data.length===0)) alert('更新失敗或無權限 (請檢查 RLS)');
    else {
      setNotes(prev => prev.map(n => n.id === id ? { ...n, is_deleted: !currentStatus } : n));
      if (isAdmin) fetchAllUsers();
    }
    setLoading(false);
  };

  const handleChangePassword = async () => {
    if (pwdTargetUser === 'SELF') {
      const { error } = await supabase.auth.updateUser({ password: newPassword });
      if (error) alert(error.message); else alert('成功');
    } else {
      if (process.env.NEXT_PUBLIC_SUPABASE_URL) alert('請至後端發送重設信');
      else alert('[模擬] 密碼已重設');
    }
    setShowPwdModal(false);
  };

  // [修正] 管理員新增使用者，並同步寫入 user_permissions
  const handleAdminAddUser = async () => {
     if(!addUserName || !addUserLast4 || !addUserPwd) return alert('請輸入完整資料');
     const email = encodeName(addUserName+addUserLast4) + FAKE_DOMAIN;
     
     setLoading(true);

     // 1. 註冊 Supabase Auth User
     const { error } = await supabase.auth.signUp({ 
         email: email, 
         password: addUserPwd, 
         options: { data: { display_name: addUserName, id_last4: addUserLast4 } } 
     });

     if (error) {
         alert('Auth 註冊失敗: ' + error.message);
         setLoading(false);
         return;
     }

     // 2. 同步寫入 user_permissions (因為 RLS 允許 insert，所以即使登入身分改變也能寫入)
     const { error: permError } = await supabase.from('user_permissions').insert([{ 
         email: email, 
         is_admin: false, 
         is_disabled: false, 
         user_name: addUserName, 
         id_last4: addUserLast4 
     }]);
     
     if (permError) {
         alert('使用者已建立，但權限表寫入失敗: ' + permError.message);
     } else {
        alert('建立成功');
        // 重置表單
        setAddUserName('');
        setAddUserLast4('');
        setAddUserPwd('');
        fetchAllUsers();
     }
     setLoading(false);
  };

  const handleAdminDeleteUser = async (targetId: string) => {
     alert('請至 Supabase Dashboard 刪除');
  };

  const handleToggleUserDisabled = async (email: string, status: boolean) => {
      const { error } = await supabase.from('user_permissions').update({ is_disabled: !status }).eq('email', email);
      if(!error) fetchAllUsers();
  };

  const fetchAllUsers = useCallback(async () => {
    const { data: pData } = await supabase.from('user_permissions').select('*').order('created_at', { ascending: false });
    const { data: nData } = await supabase.from('notes').select('sign_name, id_2, real_name, dharma_name');
    
    let notesData: any[] = [];
    if(nData) notesData = nData;

    if(pData) {
        const list = pData.map((u: any) => {
            const matchName = `${u.user_name} (${u.id_last4})`;
            const count = notesData.filter((n: any) => n.sign_name === matchName).length;
            const note = notesData.find((n:any) => n.real_name === u.user_name && n.dharma_name);
            return { ...u, display_name: u.user_name, count, dharma: note?.dharma_name };
        });
        setAllUsers(list);
    }
  }, [supabase]);

  useEffect(() => { if (activeTab === 'admin_users' && isAdmin) fetchAllUsers(); }, [activeTab, isAdmin, fetchAllUsers]);

  const fetchBulletins = async () => {
    const { data } = await supabase.from('bulletins').select('*').order('created_at', { ascending: false });
    if(data) setBulletins(data);
  };

  const fetchNotes = async (targetUser: any = user) => {
    const { data } = await supabase.from('notes').select('*').order('start_date', { ascending: true }).order('start_time', { ascending: true });
    if(data) setNotes(data);
  };

  useEffect(() => {
    const init = async () => {
        const { data: { user } } = await supabase.auth.getUser();
        setUser(user);
        if(user) {
            setFormData(prev => ({...prev, real_name: getDisplayNameOnly(user.email||'')}));
            fetchNotes(user);
            fetchBulletins();
            fetchOptions();
            checkUserStatus(user.email||'');
        }
    };
    init();
  }, [fetchOptions, checkUserStatus]);

  const handleSubmit = async () => {
    if (!user) return alert('請先登入');
    if (!formData.team_big || !formData.start_date) return alert('請填寫必填欄位');
    
    if (formData.start_date < minStartDate) return alert(`發心起日必須大於今日 (最早: ${minStartDate})`);
    if (formData.end_date < formData.start_date) return alert('發心迄日錯誤');

    const signNameOnly = getDisplayNameOnly(user.email||'');
    const { error } = await supabase.from('notes').insert([{ ...formData, id_2: getIdLast4FromEmail(user.email||''), user_id: user.id, sign_name: signNameOnly, is_deleted: false }]);
    
    if(error) alert(error.message);
    else {
        alert('成功');
        fetchNotes();
        if(isAdmin) fetchAllUsers();
        setActiveTab('history');
    }
  };

  const handleLogin = async () => {
    const email = encodeName(username+idLast4) + FAKE_DOMAIN;
    const { data, error } = await supabase.auth.signInWithPassword({ email, password });
    if(error) alert('登入失敗');
    else {
        setUser(data.user);
        checkUserStatus(email);
    }
  };

  // [修正] 自行註冊時，也同步寫入 user_permissions
  const handleSignUp = async () => {
      const email = encodeName(username+idLast4) + FAKE_DOMAIN;
      const { error } = await supabase.auth.signUp({ email, password, options: { data: { display_name: username, id_last4: idLast4 } } });
      if(error) alert(error.message);
      else {
          const { error: permError } = await supabase.from('user_permissions').insert([{ 
              email, 
              is_admin: false, 
              is_disabled: false, 
              user_name: username, 
              id_last4: idLast4    
          }]);
          
          if(permError) console.error('Perm insert fail', permError);

          alert('註冊成功');
          window.location.reload();
      }
  };

  const openPwdModal = (target: any) => {
    setPwdTargetUser(target);
    setNewPassword('');
    setShowPwdModal(true);
  };

  return (
    <div className="min-h-screen bg-amber-50 flex flex-col items-center py-10 px-4 font-sans text-gray-900">
      <h1 className="text-3xl font-bold text-amber-900 mb-8 tracking-wide">一一報名系統</h1>

      {!user ? (
        <div className="bg-white p-8 rounded-xl shadow-lg w-full max-w-sm border border-amber-200">
          <h2 className="text-xl font-bold mb-6 text-center text-gray-700">{isLoginMode ? '登入' : '註冊'}</h2>
          <div className="space-y-4">
            <input type="text" placeholder="姓名" value={username} onChange={e => setUsername(e.target.value)} className="w-full p-3 border rounded" />
            <input type="text" placeholder="身分證後四碼" maxLength={4} value={idLast4} onChange={e => setIdLast4(e.target.value)} className="w-full p-3 border rounded" />
            <input type="password" placeholder="密碼" value={password} onChange={e => setPassword(e.target.value)} className="w-full p-3 border rounded" />
          </div>
          <div className="mt-6">
             {isLoginMode ? 
                <button onClick={handleLogin} className="w-full bg-amber-700 text-white py-3 rounded">登入</button> :
                <button onClick={handleSignUp} className="w-full bg-green-700 text-white py-3 rounded">註冊</button>
             }
             <button onClick={() => setIsLoginMode(!isLoginMode)} className="w-full text-sm text-gray-500 mt-4 underline">{isLoginMode ? '沒有帳號？註冊' : '已有帳號？登入'}</button>
          </div>
        </div>
      ) : (
        <div className="w-full max-w-6xl animate-fade-in">
          <div className="flex justify-between items-center mb-6 bg-white p-4 rounded-xl shadow-sm border border-amber-100">
             <div className="flex items-center gap-3">
               <div className={`w-8 h-8 rounded-full flex items-center justify-center font-bold ${isAdmin ? 'bg-red-100 text-red-800' : 'bg-amber-100 text-amber-800'}`}>
                 {(getDisplayNameOnly(user.email||''))[0]}
               </div>
               <div>
                  <span className="font-bold">{getDisplayNameOnly(user.email||'')}</span>
                  <span className="text-xs text-gray-500 ml-2">ID: {getIdLast4FromEmail(user.email||'')}</span>
                  {isAdmin && <span className="ml-2 text-xs bg-red-500 text-white px-2 py-0.5 rounded">管理員</span>}
               </div>
             </div>
             <div className="flex gap-2">
               <button onClick={() => { setPwdTargetUser('SELF'); setShowPwdModal(true); }} className="text-sm border px-3 py-1 rounded">修改密碼</button>
               <button onClick={handleLogout} className="text-sm border px-3 py-1 rounded">登出</button>
             </div>
          </div>

          {/* Navigation */}
          <div className="flex mb-6 bg-amber-100 p-1 rounded-lg w-full overflow-x-auto">
            <button onClick={() => setActiveTab('bulletin')} className={`flex-1 py-3 px-2 whitespace-nowrap rounded-md font-bold transition-all ${activeTab === 'bulletin' ? 'bg-white text-amber-800 shadow-sm' : 'text-amber-600 hover:bg-amber-200/50'}`}>📢 公告欄</button>
            <button onClick={() => setActiveTab('form')} className={`flex-1 py-3 px-2 whitespace-nowrap rounded-md font-bold transition-all ${activeTab === 'form' ? 'bg-white text-amber-800 shadow-sm' : 'text-amber-600 hover:bg-amber-200/50'}`}>📝 我要報名</button>
            <button onClick={() => setActiveTab('history')} className={`flex-1 py-3 px-2 whitespace-nowrap rounded-md font-bold transition-all ${activeTab === 'history' ? 'bg-white text-amber-800 shadow-sm' : 'text-amber-600 hover:bg-amber-200/50'}`}>📋 我的紀錄</button>
            {isAdmin && (
              <>
                <button onClick={() => setActiveTab('admin_data')} className={`flex-1 py-3 px-2 whitespace-nowrap rounded-md font-bold transition-all ${activeTab === 'admin_data' ? 'bg-red-50 text-red-800 shadow-sm border border-red-200' : 'text-red-600 hover:bg-red-50/50'}`}>📊 全部報名資料</button>
                <button onClick={() => setActiveTab('admin_users')} className={`flex-1 py-3 px-2 whitespace-nowrap rounded-md font-bold transition-all ${activeTab === 'admin_users' ? 'bg-blue-50 text-blue-800 shadow-sm border border-blue-200' : 'text-blue-600 hover:bg-blue-50/50'}`}>👥 使用者</button>
                <button onClick={() => setActiveTab('admin_settings')} className={`flex-1 py-3 px-2 whitespace-nowrap rounded-md font-bold transition-all ${activeTab === 'admin_settings' ? 'bg-gray-700 text-white shadow-sm border border-gray-600' : 'text-gray-600 hover:bg-gray-200/50'}`}>⚙️ 系統設定</button>
              </>
            )}
          </div>

          {/* Content */}
          {activeTab === 'bulletin' && (
             <div className="space-y-6">
                {isAdmin && (
                  <div className="bg-white p-4 rounded shadow border border-orange-200 mb-4">
                    <textarea value={bulletinText} onChange={e => setBulletinText(e.target.value)} className="w-full border p-2 mb-2" placeholder="公告內容..."></textarea>
                    <div className="flex justify-between">
                       <input type="file" ref={fileInputRef} onChange={handleImageUpload} />
                       <button onClick={handlePostBulletin} className="bg-orange-500 text-white px-4 py-2 rounded">發布</button>
                    </div>
                  </div>
                )}
                {bulletins.map(b => (
                   <div key={b.id} className="bg-white p-6 rounded shadow relative">
                      {isAdmin && <button onClick={() => handleDeleteBulletin(b.id)} className="absolute top-4 right-4 text-red-500">刪除</button>}
                      <p className="whitespace-pre-wrap mb-4">{b.content}</p>
                      {b.image_url && <img src={b.image_url} className="max-w-full rounded" />}
                   </div>
                ))}
             </div>
          )}

          {activeTab === 'form' && (
             <div className="bg-white p-6 rounded shadow border border-amber-200">
               <h3 className="text-xl font-bold text-amber-900 mb-4">發心報名</h3>
               <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
                  <div>
                    <label className="block text-sm mb-1">1. 大隊 <span className="text-red-500">*</span></label>
                    <select className="w-full border p-2 rounded" value={formData.team_big} onChange={e => setFormData({...formData, team_big: e.target.value})}>
                      {teamBigOptions.map(o => <option key={o.id} value={o.value}>{o.value}</option>)}
                    </select>
                  </div>
                  <div>
                    <label className="block text-sm mb-1">2. 小隊 <span className="text-red-500">*</span></label>
                    <select className="w-full border p-2 rounded" value={formData.team_small} onChange={e => setFormData({...formData, team_small: e.target.value})}>
                      {teamSmallOptions.map(o => <option key={o.id} value={o.value}>{o.value}</option>)}
                    </select>
                  </div>
                  <div><label className="block text-sm mb-1">3. 精舍 <span className="text-red-500">*</span></label><input className="w-full border p-2 rounded" value={formData.monastery} onChange={e => setFormData({...formData, monastery: e.target.value})} /></div>
                  <div><label className="block text-sm mb-1">4. 姓名 <span className="text-red-500">*</span></label><input className="w-full border p-2 rounded" value={formData.real_name} onChange={e => setFormData({...formData, real_name: e.target.value})} /></div>
                  <div><label className="block text-sm mb-1">5. 法名</label><input className="w-full border p-2 rounded" value={formData.dharma_name} onChange={e => setFormData({...formData, dharma_name: e.target.value})} /></div>
                  <div>
                    <label className="block text-sm mb-1">6. 新增異動 <span className="text-red-500">*</span></label>
                    <select className="w-full border p-2 rounded" value={formData.action_type} onChange={e => setFormData({...formData, action_type: e.target.value})}>
                      <option value="新增">新增</option><option value="異動">異動</option>
                    </select>
                  </div>
                  <div className="lg:col-span-2"><label className="block text-sm mb-1">7. 發心起 <span className="text-red-500">*</span></label><div className="flex gap-2"><input type="date" min={minStartDate} className="border p-2 rounded flex-1" value={formData.start_date} onChange={e => setFormData({...formData, start_date: e.target.value})} /><input type="time" className="border p-2 rounded flex-1" value={formData.start_time} onChange={e => setFormData({...formData, start_time: e.target.value})} /></div></div>
                  <div className="lg:col-span-2"><label className="block text-sm mb-1">8. 發心迄 <span className="text-red-500">*</span></label><div className="flex gap-2"><input type="date" min={formData.start_date} className="border p-2 rounded flex-1" value={formData.end_date} onChange={e => setFormData({...formData, end_date: e.target.value})} /><input type="time" className="border p-2 rounded flex-1" value={formData.end_time} onChange={e => setFormData({...formData, end_time: e.target.value})} /></div></div>
                  <div className="md:col-span-2 lg:col-span-4"><label className="flex items-center gap-2 cursor-pointer"><input type="checkbox" checked={formData.need_help} onChange={e => setFormData({...formData, need_help: e.target.checked})} /> 9. 是否需要協助報名 (是)</label><p className="text-xs text-gray-500 ml-6">若在普台學校及中台週邊的居士，需師父協助報名，請勾選。</p></div>
                  <div className="md:col-span-2 lg:col-span-4"><label className="block text-sm mb-1">10. 備註</label><textarea className="w-full border p-2 rounded" rows={2} value={formData.memo} onChange={e => setFormData({...formData, memo: e.target.value})}></textarea></div>
               </div>
               <button onClick={handleSubmit} className="w-full bg-amber-700 text-white py-3 rounded mt-6">送出</button>
             </div>
          )}

          {activeTab === 'history' && (
             <div className="space-y-4">
               {notes.filter(n => n.user_id === user?.id).map(n => (
                 <div key={n.id} className={`bg-white p-4 rounded shadow border relative ${n.is_deleted ? 'opacity-50' : ''}`}>
                    {n.is_deleted && <span className="absolute top-0 left-0 bg-red-500 text-white text-xs px-2 py-1">已刪除</span>}
                    <div className="flex justify-between mb-2"><span className="font-bold">{n.team_big} - {n.team_small}</span><span>{n.action_type}</span></div>
                    <div className="text-sm grid grid-cols-2 gap-2">
                      <p>姓名: {n.real_name}</p><p>法名: {n.dharma_name}</p>
                      <p>起: {n.start_date} {n.start_time}</p><p>迄: {n.end_date} {n.end_time}</p>
                    </div>
                    <div className="mt-2 pt-2 border-t text-xs text-gray-500 flex justify-between items-center">
                       <span>填表人: {n.sign_name} ({n.id_2})</span>
                       <label className="flex items-center gap-1 cursor-pointer"><span className="text-red-500">刪除</span><input type="checkbox" checked={n.is_deleted} onChange={() => handleToggleDeleteNote(n.id, n.is_deleted)} /></label>
                    </div>
                 </div>
               ))}
             </div>
          )}

          {activeTab === 'admin_data' && isAdmin && (
             <div className="bg-white p-6 rounded shadow">
                <div className="flex justify-between mb-4">
                   <h3 className="font-bold text-lg">全部報名資料</h3>
                   <button onClick={exportToExcel} className="bg-green-600 text-white px-4 py-2 rounded">匯出 Excel</button>
                </div>
                <div className="overflow-x-auto">
                  <table className="w-full text-sm text-left">
                    <thead className="bg-gray-50"><tr><th className="p-2">狀態</th><th className="p-2">大隊/小隊</th><th className="p-2">姓名</th><th className="p-2">法名</th><th className="p-2">填表人</th></tr></thead>
                    <tbody>
                      {notes.map(n => (
                        <tr key={n.id} className="border-b">
                          <td className="p-2">{n.action_type} {n.is_deleted && '(刪)'}</td>
                          <td className="p-2">{n.team_big}/{n.team_small}</td>
                          <td className="p-2">{n.real_name}</td>
                          <td className="p-2">{n.dharma_name}</td>
                          <td className="p-2 text-blue-600">{n.sign_name} ({n.id_2})</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
             </div>
          )}

          {activeTab === 'admin_users' && isAdmin && (
             <div className="bg-white p-6 rounded shadow">
                <h3 className="font-bold text-lg mb-4">使用者管理 <span className="text-xs font-normal text-red-500 ml-2">(修改資料請至後端)</span></h3>
                <table className="w-full text-sm text-left">
                    <thead className="bg-gray-50"><tr><th className="p-2">填表人 (法名)</th><th className="p-2">ID</th><th className="p-2">狀態</th><th className="p-2 text-right">筆數</th><th className="p-2 text-right">操作</th></tr></thead>
                    <tbody>
                      {allUsers.map(u => (
                        <tr key={u.id} className="border-b">
                          <td className="p-2">{u.display_name} {u.dharma ? `(${u.dharma})` : ''}</td>
                          <td className="p-2">{u.id_last4}</td>
                          <td className="p-2">{u.is_disabled ? '禁用' : '正常'}</td>
                          <td className="p-2 text-right">{u.count}</td>
                          <td className="p-2 text-right"><button onClick={() => handleToggleUserDisabled(u.email, u.is_disabled)} className="text-blue-500">{u.is_disabled ? '啟用' : '禁用'}</button></td>
                        </tr>
                      ))}
                    </tbody>
                </table>
             </div>
          )}

          {activeTab === 'admin_settings' && isAdmin && (
             <div className="bg-white p-6 rounded shadow">
                <h3 className="font-bold text-lg mb-4">系統設定</h3>
                <div className="grid grid-cols-2 gap-8">
                   <div>
                      <h4 className="font-bold mb-2">大隊</h4>
                      <ul>{teamBigOptions.map(o => <li key={o.id} className="flex justify-between border-b p-1"><span>{o.value}</span><button onClick={() => handleDeleteOption(o.id)} className="text-red-500 text-xs">刪除</button></li>)}</ul>
                      <div className="mt-2 flex gap-1"><input className="border p-1 flex-1" placeholder="新增..." value={selectedCategory==='team_big'?newOptionValue:''} onChange={e => {setNewOptionValue(e.target.value); setSelectedCategory('team_big')}} /><button onClick={() => handleAddOption('team_big')} className="bg-gray-200 px-2 rounded">➕</button></div>
                      <button onClick={handleInitializeDefaults} className="text-xs text-blue-500 mt-2 underline">匯入預設選項</button>
                   </div>
                   <div>
                      <h4 className="font-bold mb-2">小隊</h4>
                      <ul>{teamSmallOptions.map(o => <li key={o.id} className="flex justify-between border-b p-1"><span>{o.value}</span><button onClick={() => handleDeleteOption(o.id)} className="text-red-500 text-xs">刪除</button></li>)}</ul>
                      <div className="mt-2 flex gap-1"><input className="border p-1 flex-1" placeholder="新增..." value={selectedCategory==='team_small'?newOptionValue:''} onChange={e => {setNewOptionValue(e.target.value); setSelectedCategory('team_small')}} /><button onClick={() => handleAddOption('team_small')} className="bg-gray-200 px-2 rounded">➕</button></div>
                   </div>
                </div>
             </div>
          )}
          
          {showPwdModal && (
             <div className="fixed inset-0 bg-black/50 flex items-center justify-center p-4">
                <div className="bg-white p-6 rounded shadow-lg w-full max-w-sm">
                   <h3 className="font-bold mb-4">修改密碼</h3>
                   <input type="password" placeholder="新密碼" className="w-full border p-2 mb-4 rounded" value={newPassword} onChange={e => setNewPassword(e.target.value)} />
                   <div className="flex justify-end gap-2"><button onClick={() => setShowPwdModal(false)} className="px-4 py-2 bg-gray-200 rounded">取消</button><button onClick={handleChangePassword} className="px-4 py-2 bg-blue-600 text-white rounded">確認</button></div>
                </div>
             </div>
          )}

        </div>
      )}
    </div>
  );
}